##默认使用配置
#spring:
#  profiles:
#    active: dev
##公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mybatis:
#  typeAliasesPackage: com.yj.dao
#  mapperLocations: classpath*:com/yj/*/*.xml
#
#---
#
##开发配置
#spring:
#  profiles: dev
#
#  datasource:
#    url: jdbc:mysql://120.78.128.25/future_db_release
#    username: lemon
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
##    maxActive: 20
##    initialSize: 1
##    maxWait: 60000
##    minIdle: 1
##    timeBetweenEvictionRunsMillis: 60000
##    minEvictableIdleTimeMillis: 300000
##    validationQuery: select 'x'
##    testWhileIdle: true
##    testOnBorrow: false
##    testOnReturn: false
##    poolPreparedStatements: true
##    maxOpenPreparedStatements: 20
#
#    # 使用druid数据源
#    #type: com.alibaba.druid.pool.DruidDataSource